### ISSUE TITLE
HTML Notifications script requires version 3+ of PowerShell

### ISSUE THREAD

**Issue by andrewmumblebee** [squaredup/Scripts#4]
There is a cmdlet used in the script which is only supported in version 3+ of PowerShell

![image](https://user-images.githubusercontent.com/29373199/27030009-8c8230b2-4f62-11e7-928b-e55000bc5a64.png)

Haven't had a chance to look into which cmdlet, but hope this helps! 💃

**Comment by shadeon** [comment]
Hi Andrew, sorry for taking long to look at this.  Rather than a function, it's a validation attribute on one of the internal functions - probably an undocumented feature that came in version 3 or a fixed bug.

Should be a simple matter of swapping it out for a supported call or using manual validation for that parameter.
